// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6gWWaUPgS22DC3h-9kpKI51X_6C_cSe0',
    appId: '1:220906854342:web:1e4260b08a788d8d5104c7',
    messagingSenderId: '220906854342',
    projectId: 'auth-app-project-darsh',
    authDomain: 'auth-app-project-darsh.firebaseapp.com',
    storageBucket: 'auth-app-project-darsh.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGIttJPfBV8HKvY36zANmnuwpfzWNNaq0',
    appId: '1:220906854342:android:14f3bc203565d3cc5104c7',
    messagingSenderId: '220906854342',
    projectId: 'auth-app-project-darsh',
    storageBucket: 'auth-app-project-darsh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-fLZremibMUephpdMGQ5obvAREH0iYC0',
    appId: '1:220906854342:ios:a5ea72dea3a76e8c5104c7',
    messagingSenderId: '220906854342',
    projectId: 'auth-app-project-darsh',
    storageBucket: 'auth-app-project-darsh.firebasestorage.app',
    iosBundleId: 'com.example.authenticationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-fLZremibMUephpdMGQ5obvAREH0iYC0',
    appId: '1:220906854342:ios:a5ea72dea3a76e8c5104c7',
    messagingSenderId: '220906854342',
    projectId: 'auth-app-project-darsh',
    storageBucket: 'auth-app-project-darsh.firebasestorage.app',
    iosBundleId: 'com.example.authenticationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6gWWaUPgS22DC3h-9kpKI51X_6C_cSe0',
    appId: '1:220906854342:web:be10d356f498a9fb5104c7',
    messagingSenderId: '220906854342',
    projectId: 'auth-app-project-darsh',
    authDomain: 'auth-app-project-darsh.firebaseapp.com',
    storageBucket: 'auth-app-project-darsh.firebasestorage.app',
  );

}